<?xml version="1.0"?>
<package format="3">
  <name>mecanum_navigation</name>
  <version>0.1.0</version>
  <description>AMCL, map_server, slam_toolbox, EKF, Nav2, Velocity Smoother ve Collision Monitor konfigurasyonlari; haritalar ve ortam profilleri</description>

  <maintainer email="esat@example.com">Esat</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_smac_planner</exec_depend>
  <exec_depend>nav2_mppi_controller</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>robot_localization</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
